from __future__ import annotations

from collections import Counter
from datetime import datetime
from typing import Any

from har2jmx.models import BuildResult
from har2jmx.patterns import CLASSIFICATION_LABELS, TOKEN_NAME_RE


def _md_escape(value: str) -> str:
    return str(value or "").replace("|", "\\|").replace("\n", " ")


def _report_label(filename: str) -> str:
    if filename.startswith("README"):
        return "README — start here"
    if filename.startswith("CORRELATION_REPORT"):
        return "Correlation Report"
    if filename.startswith("PARAMETERIZATION_REPORT"):
        return "Parameterization Report"
    if filename.startswith("REPLAY_VALIDATION_REPORT"):
        return "Replay Validation Report"
    if filename.startswith("MANUAL_REVIEW_REPORT"):
        return "Manual Review Report"
    return filename


def build_summary(result: BuildResult) -> dict[str, Any]:
    method_counts = Counter(s.method for s in result.samplers)
    domain_counts = Counter(s.domain for s in result.samplers if s.domain)
    status_counts = Counter(str(s.status) for s in result.samplers if s.status != "")
    transactions = Counter(s.transaction for s in result.samplers)
    avg_time = round(sum(s.time_ms for s in result.samplers) / len(result.samplers)) if result.samplers else 0
    dynamic_hits = len(result.parameters) + len(result.correlations)
    filtered_entries = max(result.total_entries - len(result.samplers), 0)
    low_confidence = [c for c in result.correlations if c.confidence == "Low"] + [p for p in result.parameters if p.confidence == "Low"]
    has_auth_signal = any(c.field == "headers" or TOKEN_NAME_RE.search(c.variable) for c in result.correlations)
    readiness_score = result.quality_gate_score if result.quality_gate_score > 0 else min(
        100,
        45
        + min(len(result.samplers), 20)
        + min(len(transactions) * 4, 16)
        + min(dynamic_hits * 5, 25)
        + (10 if filtered_entries else 0),
    )
    correlation_completeness = min(100, 50 + min(len(result.correlations) * 6, 50)) if result.samplers else 0
    parameterization_completeness = min(100, 50 + min(len(result.parameters) * 5, 50)) if result.samplers else 0
    auth_handling = 90 if has_auth_signal else (40 if result.correlations else 20)
    maintainability = 85 if filtered_entries else 70
    category_scores = {
        "correlationCompleteness": correlation_completeness,
        "parameterizationCompleteness": parameterization_completeness,
        "authenticationHandling": auth_handling,
        "maintainability": maintainability,
        "performanceReadiness": readiness_score,
    }
    manual_work_items = []
    if low_confidence:
        manual_work_items.append(f"Review {len(low_confidence)} Low-confidence parameter/correlation guess(es) before running load.")
    if not has_auth_signal:
        manual_work_items.append("No clear authentication token/session was detected; confirm login is captured and replays correctly.")
    if any(str(code).startswith(("4", "5")) for code in status_counts):
        manual_work_items.append("HAR contains 4xx/5xx responses; confirm these are expected baseline errors.")
    if not result.samplers:
        manual_work_items.append("No application/API requests were detected after filtering.")
    review_notes = list(manual_work_items)
    if filtered_entries:
        review_notes.append(f"{filtered_entries} static/noise request(s) were excluded from the JMX.")
    if result.overlap_removed:
        review_notes.append(
            f"{result.overlap_removed} value(s) matched a business-data name pattern but were already proven "
            "dynamically generated by a correlation -- kept as correlated extractors only, not duplicated into CSV/UDV."
        )
    if result.auto_corrections:
        for correction in result.auto_corrections:
            review_notes.append(f"Auto-corrected ({correction.rule}): {correction.action} — {correction.detail}")
    if result.entities:
        entity_names = ", ".join(e.name for e in result.entities)
        review_notes.append(
            f"Generated {len(result.entities)} separate CSV file(s) by business entity ({entity_names}), "
            f"{result.csv_row_count} representative rows each -- identifiers varied, dates shifted by day, "
            "passwords/PINs and free-text fields kept constant. Review the values before a real run."
        )
    failed_checks = [v for v in result.validation_results if not v.passed]
    for v in failed_checks:
        review_notes.append(f"Replay validation: {v.check} -- {v.detail}")
    if result.enterprise_apps:
        review_notes.append(f"Detected platform(s): {', '.join(result.enterprise_apps)} — verify platform-specific session/token handling.")
    return {
        "testName": result.test_name,
        "samplers": len(result.samplers),
        "transactions": len({s.transaction for s in result.samplers}),
        "filteredEntries": filtered_entries,
        "totalEntries": result.total_entries,
        "readinessScore": readiness_score,
        "categoryScores": category_scores,
        "manualWorkItems": manual_work_items,
        "manualWorkPercent": max(0, 100 - readiness_score),
        "enterpriseApps": result.enterprise_apps,
        "avgResponseTimeMs": avg_time,
        "methods": dict(method_counts.most_common()),
        "domains": dict(domain_counts.most_common(5)),
        "statuses": dict(status_counts.most_common()),
        "transactionNames": [
            {"name": name, "count": count}
            for name, count in transactions.most_common(12)
        ],
        "endpoints": [
            {
                "method": sampler.method,
                "path": sampler.path,
                "status": sampler.status,
                "timeMs": sampler.time_ms,
                "transaction": sampler.transaction,
            }
            for sampler in result.samplers[:12]
        ],
        "parameters": [
            {k: v for k, v in parameter.__dict__.items() if k != "source_samplers"}
            for parameter in result.parameters[:50]
        ],
        "correlations": [
            {
                "variable": rule.variable,
                "source_sampler": rule.source_sampler,
                "field": rule.field,
                "pattern": rule.pattern,
                "confidence": rule.confidence,
                "reason": rule.reason,
                "extractor": rule.extractor,
                "classification": rule.classification,
                "classificationLabel": CLASSIFICATION_LABELS.get(rule.classification, rule.classification),
                "origin": rule.origin,
                "consumers": list(rule.consumers),
            }
            for rule in result.correlations[:50]
        ],
        "reviewNotes": review_notes,
        "jmx": result.jmx_path.name,
        "csvFiles": [
            {"entity": entity.name, "filename": path.name, "columns": [p.name for p in entity.parameters]}
            for entity, path in zip(result.entities, result.csv_paths)
        ],
        "reports": [
            {"filename": path.name, "label": _report_label(path.name)}
            for path in result.report_paths
        ],
        "validationChecklist": [
            {"check": v.check, "passed": v.passed, "detail": v.detail}
            for v in result.validation_results
        ],
        "qualityGate": {
            "passed": result.quality_gate_passed,
            "score": result.quality_gate_score,
            "label": (
                "Production ready" if result.quality_gate_score >= 90
                else "Good — minor review recommended" if result.quality_gate_score >= 70
                else "Needs review before production use"
            ),
        },
        "autoCorrections": [
            {"rule": c.rule, "action": c.action, "detail": c.detail}
            for c in result.auto_corrections
        ],
        "download": result.bundle_path.name if result.bundle_path else result.jmx_path.name,
        "downloadIsBundle": result.bundle_path is not None,
        "generatedAt": datetime.now().isoformat(timespec="seconds"),
    }


def build_correlation_report(result: BuildResult) -> str:
    lines = [
        "# Correlation Report",
        "",
        f"**Script:** {result.test_name}",
        f"**Generated:** {datetime.now().isoformat(timespec='seconds')}",
        f"**Total correlations:** {len(result.correlations)}",
        "",
        "Every value below was proven to originate in a server response AND be",
        "consumed by at least one later request in this HAR — no value was",
        "correlated merely because it repeated or looked random.",
        "",
        "| Variable | Classification | Confidence | Extractor | Source Request | Consumed By |",
        "|---|---|---|---|---|---|",
    ]
    for c in result.correlations:
        label = CLASSIFICATION_LABELS.get(c.classification, c.classification)
        extractor_label = {"json": "JSON Extractor", "css": "CSS Selector", "regex": "Regex Extractor"}.get(c.extractor, c.extractor)
        consumers = ", ".join(c.consumers[:3]) + (f" (+{len(c.consumers) - 3} more)" if len(c.consumers) > 3 else "")
        lines.append(
            f"| `${{{_md_escape(c.variable)}}}` | {c.classification} — {label} | {c.confidence} | "
            f"{extractor_label} | {_md_escape(c.source_sampler)} | {_md_escape(consumers)} |"
        )
    if not result.correlations:
        lines.append("| _(none detected)_ | | | | | |")
    lines += [
        "",
        "## Classification legend",
        "- **A** — Business Input (handled in the Parameterization Report, not here)",
        "- **B** — Runtime Object Identifier (product ID, customer ID, order ID, etc.)",
        "- **C** — Session Identifier (cookie-based session)",
        "- **D** — Security Identifier (CSRF/XSRF/bearer/auth token)",
        "- **E** — Temporary Identifier (GUID/UUID with no stable business name)",
        "- **F** — Static Constant (never correlated or parameterized)",
        "",
        "## What to review manually",
        f"- {sum(1 for c in result.correlations if c.confidence == 'Low')} Low-confidence correlation(s) — verify these extractors match the real response shape before a full run.",
        f"- {sum(1 for c in result.correlations if not c.consumers)} correlation(s) with no downstream consumer in this capture — likely the last step recorded; harmless, but confirm.",
    ]
    return "\n".join(lines)


def build_parameterization_report(result: BuildResult) -> str:
    lines = [
        "# Parameterization Report",
        "",
        f"**Script:** {result.test_name}",
        f"**Generated:** {datetime.now().isoformat(timespec='seconds')}",
        f"**Total business inputs:** {len(result.parameters)}",
        f"**CSV files generated:** {len(result.entities)}",
        "",
        "Every value below was found in a REQUEST (not a response) and matched",
        "a business-data naming pattern. Values proven to be server-generated",
        "(see the Correlation Report) are explicitly excluded, even if their",
        "name looked like business data.",
        "",
    ]
    for entity, path in zip(result.entities, result.csv_paths):
        lines.append(f"## {entity.name}.csv — `{path.name}`")
        lines.append("")
        lines.append("| Column | Sample Value | Occurrences | Confidence | Reason |")
        lines.append("|---|---|---|---|---|")
        for p in entity.parameters:
            lines.append(
                f"| `${{{_md_escape(p.name)}}}` | {_md_escape(p.value)} | {p.occurrences} | "
                f"{p.confidence} | {_md_escape(p.reason)} |"
            )
        lines.append("")
    if not result.entities:
        lines.append("_No business-input parameters were identified in this capture._")
    lines += [
        "## What to review manually",
        f"- {sum(1 for p in result.parameters if p.confidence == 'Low')} Low-confidence parameter(s) — confirm these are genuinely user-entered before relying on the generated test data.",
        "- Each CSV currently has representative rows generated from the single captured value (identifiers varied, dates shifted by day, passwords/PINs kept constant). Replace with real test data before a production run.",
    ]
    return "\n".join(lines)


def build_replay_validation_report(result: BuildResult) -> str:
    gate_label = (
        "Production ready" if result.quality_gate_score >= 90
        else "Good — minor review recommended" if result.quality_gate_score >= 70
        else "Needs review before production use"
    )
    lines = [
        "# Replay Validation Report",
        "",
        f"**Script:** {result.test_name}",
        f"**Generated:** {datetime.now().isoformat(timespec='seconds')}",
        f"**Quality gate score:** {result.quality_gate_score}/100 — {gate_label}",
        f"**Gate result:** {'PASSED' if result.quality_gate_passed else 'NEEDS REVIEW'}",
        "",
        "## Auto-corrections applied",
        "",
    ]
    if result.auto_corrections:
        for c in result.auto_corrections:
            lines.append(f"- **[{c.rule}]** {c.action} — {c.detail}")
    else:
        lines.append("_No automatic corrections were required._")
    lines += ["", "## Validation checklist", "", "| Result | Check | Detail |", "|---|---|---|"]
    for v in result.validation_results:
        mark = "PASS" if v.passed else "FAIL"
        lines.append(f"| {mark} | {_md_escape(v.check)} | {_md_escape(v.detail)} |")
    return "\n".join(lines)


def build_manual_review_report(result: BuildResult) -> str | None:
    if result.quality_gate_score >= 95:
        return None

    failed_checks = [v for v in result.validation_results if not v.passed]
    low_conf_correlations = [c for c in result.correlations if c.confidence == "Low"]
    low_conf_parameters = [p for p in result.parameters if p.confidence == "Low"]

    lines = [
        "# Manual Review Report",
        "",
        f"**Script:** {result.test_name}",
        f"**Quality gate score:** {result.quality_gate_score}/100 (below the 95 confidence threshold for a clean hand-off)",
        "",
        "This report only exists because the script scored below 95/100. Items",
        "below are what a Performance Engineer should check before running this",
        "script at scale.",
        "",
        "## Failed validation checks",
        "",
    ]
    if failed_checks:
        for v in failed_checks:
            lines.append(f"- **{v.check}** — {v.detail}")
    else:
        lines.append("_None — all validation checks passed; the score was reduced by advisory items below._")

    lines += ["", "## Low-confidence correlations", ""]
    if low_conf_correlations:
        for c in low_conf_correlations:
            lines.append(f"- `${{{c.variable}}}` from '{c.source_sampler}' — {c.reason}")
    else:
        lines.append("_None._")

    lines += ["", "## Low-confidence parameters", ""]
    if low_conf_parameters:
        for p in low_conf_parameters:
            lines.append(f"- `${{{p.name}}}` — {p.reason}")
    else:
        lines.append("_None._")

    return "\n".join(lines)


def build_readme(result: BuildResult, report_names: list[str]) -> str:
    csv_list = "\n".join(f"- `{p.name}` — {e.name} test data" for e, p in zip(result.entities, result.csv_paths)) or "- _(none — no business inputs required CSV data)_"
    reports_list = "\n".join(f"- `{name}`" for name in report_names)
    return "\n".join([
        "# Self-Healing JMeter Package",
        "",
        f"**Generated:** {datetime.now().isoformat(timespec='seconds')}",
        f"**Quality gate score:** {result.quality_gate_score}/100",
        "",
        "## Quick start",
        "1. Unzip everything in this archive into one folder (don't separate the .jmx from the .csv files).",
        f"2. Open `{result.jmx_path.name}` in JMeter 5.6 or later.",
        "3. Review the reports below, then run.",
        "",
        "## What's in this package",
        "",
        f"- `{result.jmx_path.name}` — the generated test plan",
        csv_list,
        reports_list,
        "",
        "## Reports, in the order you should read them",
        "1. **Replay Validation Report** — overall score and what the engine auto-fixed.",
        "2. **Manual Review Report** (if present) — only generated when the score is below 95; tells you exactly what to check.",
        "3. **Correlation Report** — every dynamic value the script extracts at runtime, and why.",
        "4. **Parameterization Report** — every business input wired to CSV data, and why.",
    ])
